package codegen

import (
	"fmt"
	"sort"
	"strings"

	"github.com/135yshr/meow/pkg/ast"
)

// GenerateFuzz produces Go fuzz test source from a Program AST.
// It converts fuzz_ prefixed functions into Go FuzzXxx functions.
// It returns helper code (main.go), fuzz test code (main_test.go),
// and the list of generated Go fuzz function names.
func (g *Generator) GenerateFuzz(prog *ast.Program) (helpers string, fuzzTests string, fuzzNames []string, err error) {
	type fuzzFunc struct {
		name   string
		fn     *ast.FuncStmt
		seeds  [][]ast.Expr
		params []ast.Param
	}

	var funcs []fuzzFunc
	var helperFuncs []string

	for _, stmt := range prog.Stmts {
		fn, ok := stmt.(*ast.FuncStmt)
		if !ok {
			code, err := g.genStmtOrError(stmt)
			if err != nil {
				return "", "", nil, err
			}
			if code != "" {
				g.topLevel = append(g.topLevel, code)
			}
			continue
		}
		if strings.HasPrefix(fn.Name, "fuzz_") {
			seeds := extractSeeds(fn)
			funcs = append(funcs, fuzzFunc{
				name:   fn.Name,
				fn:     fn,
				seeds:  seeds,
				params: fn.Params,
			})
		} else {
			helperFuncs = append(helperFuncs, g.genFuncDecl(fn))
		}
	}

	// Ensure testing import is registered before capturing import names
	g.ensureImport("testing")

	// Generate helpers (main.go)
	var hb strings.Builder
	hb.WriteString("// Code generated by meow compiler. DO NOT EDIT.\n")
	hb.WriteString("package main\n\n")
	hb.WriteString("import meow \"github.com/135yshr/meow/runtime/meowrt\"\n")
	importNames := make([]string, 0, len(g.imports))
	for name := range g.imports {
		importNames = append(importNames, name)
	}
	sort.Strings(importNames)
	for _, name := range importNames {
		fmt.Fprintf(&hb, "import meow_%s \"%s\"\n", name, g.imports[name])
	}
	hb.WriteString("\n")
	for _, fn := range helperFuncs {
		hb.WriteString(fn)
		hb.WriteString("\n\n")
	}
	// suppress unused imports
	hb.WriteString("var _ = meow.NewNil\n")
	hb.WriteString("var _ = meow_testing.Judge\n")

	// Generate fuzz tests (main_test.go)
	var fb strings.Builder
	fb.WriteString("// Code generated by meow compiler. DO NOT EDIT.\n")
	fb.WriteString("package main\n\n")
	fb.WriteString("import (\n")
	if len(funcs) > 0 {
		fb.WriteString("\t\"testing\"\n\n")
	}
	fb.WriteString("\tmeow \"github.com/135yshr/meow/runtime/meowrt\"\n")
	for _, name := range importNames {
		fmt.Fprintf(&fb, "\tmeow_%s \"%s\"\n", name, g.imports[name])
	}
	fb.WriteString(")\n\n")
	// suppress unused imports
	fb.WriteString("var _ = meow.NewNil\n")
	fb.WriteString("var _ = meow_testing.Judge\n\n")

	// Validate seed arity
	for _, ff := range funcs {
		for i, seed := range ff.seeds {
			if len(seed) != len(ff.params) {
				return "", "", nil, fmt.Errorf("fuzz function %s: seed %d has %d values but function takes %d parameters", ff.name, i+1, len(seed), len(ff.params))
			}
		}
	}

	var names []string
	for _, ff := range funcs {
		goName := "Fuzz" + capitalizeFirst(strings.TrimPrefix(ff.name, "fuzz_"))
		names = append(names, goName)

		fmt.Fprintf(&fb, "func %s(f *testing.F) {\n", goName)

		// Add seeds
		for _, seed := range ff.seeds {
			seedArgs := make([]string, len(seed))
			for i, s := range seed {
				seedArgs[i] = g.fuzzSeedLiteral(s)
			}
			fmt.Fprintf(&fb, "\tf.Add(%s)\n", strings.Join(seedArgs, ", "))
		}

		// Generate Fuzz function
		fuzzParams := make([]string, len(ff.params))
		fuzzParamTypes := make([]string, len(ff.params))
		for i, p := range ff.params {
			typ := g.fuzzGoType(p)
			fuzzParams[i] = fmt.Sprintf("%s_raw %s", p.Name, typ)
			fuzzParamTypes[i] = typ
		}

		fmt.Fprintf(&fb, "\tf.Fuzz(func(t *testing.T, %s) {\n", strings.Join(fuzzParams, ", "))

		// Convert raw params to meow values
		for i, p := range ff.params {
			converter := g.fuzzConverter(fuzzParamTypes[i], p.Name+"_raw")
			fmt.Fprintf(&fb, "\t\t%s := %s\n", p.Name, converter)
		}

		// Generate body (excluding seed calls)
		for _, stmt := range ff.fn.Body {
			if isSeedCall(stmt) {
				continue
			}
			fmt.Fprintf(&fb, "\t\t%s\n", g.genStmt(stmt))
		}

		fb.WriteString("\t})\n")
		fb.WriteString("}\n\n")
	}

	return hb.String(), fb.String(), names, nil
}

func extractSeeds(fn *ast.FuncStmt) [][]ast.Expr {
	var seeds [][]ast.Expr
	for _, stmt := range fn.Body {
		if es, ok := stmt.(*ast.ExprStmt); ok {
			if call, ok := es.Expr.(*ast.CallExpr); ok {
				if ident, ok := call.Fn.(*ast.Ident); ok && ident.Name == "seed" {
					seeds = append(seeds, call.Args)
				}
			}
		}
	}
	return seeds
}

func isSeedCall(stmt ast.Stmt) bool {
	es, ok := stmt.(*ast.ExprStmt)
	if !ok {
		return false
	}
	call, ok := es.Expr.(*ast.CallExpr)
	if !ok {
		return false
	}
	ident, ok := call.Fn.(*ast.Ident)
	return ok && ident.Name == "seed"
}

func (g *Generator) fuzzSeedLiteral(expr ast.Expr) string {
	switch e := expr.(type) {
	case *ast.IntLit:
		return fmt.Sprintf("int64(%d)", e.Value)
	case *ast.FloatLit:
		return fmt.Sprintf("float64(%g)", e.Value)
	case *ast.StringLit:
		return fmt.Sprintf("%q", e.Value)
	case *ast.BoolLit:
		return fmt.Sprintf("%t", e.Value)
	default:
		return "int64(0)"
	}
}

// fuzzGoType returns the Go type string for a fuzz parameter based on its type annotation.
func (g *Generator) fuzzGoType(p ast.Param) string {
	if p.TypeAnn == nil {
		return "int64" // fallback
	}
	if bt, ok := p.TypeAnn.(*ast.BasicType); ok {
		switch bt.Name {
		case "int":
			return "int64"
		case "float":
			return "float64"
		case "string":
			return "string"
		case "bool":
			return "bool"
		}
	}
	return "int64"
}

func (g *Generator) fuzzConverter(typ, rawVar string) string {
	switch typ {
	case "int64":
		return fmt.Sprintf("meow.NewInt(%s)", rawVar)
	case "float64":
		return fmt.Sprintf("meow.NewFloat(%s)", rawVar)
	case "string":
		return fmt.Sprintf("meow.NewString(%s)", rawVar)
	case "bool":
		return fmt.Sprintf("meow.NewBool(%s)", rawVar)
	default:
		return fmt.Sprintf("meow.NewInt(%s)", rawVar)
	}
}
