package codegen

import (
	"fmt"
	"sort"
	"strings"

	"github.com/135yshr/meow/pkg/ast"
	"github.com/135yshr/meow/pkg/token"
)

// GenerateFuzz produces Go fuzz test source from a Program AST.
// It converts fuzz_ prefixed functions into Go FuzzXxx functions.
// It returns helper code (main.go), fuzz test code (main_test.go),
// and the list of generated Go fuzz function names.
func (g *Generator) GenerateFuzz(prog *ast.Program) (helpers string, fuzzTests string, fuzzNames []string, err error) {
	type fuzzFunc struct {
		name   string
		fn     *ast.FuncStmt
		seeds  [][]ast.Expr
		params []ast.Param
	}

	var funcs []fuzzFunc
	var helperFuncs []string
	var fuzzBodies []string

	for _, stmt := range prog.Stmts {
		fn, ok := stmt.(*ast.FuncStmt)
		if !ok {
			code, err := g.genStmtOrError(stmt)
			if err != nil {
				return "", "", nil, err
			}
			if code != "" {
				g.topLevel = append(g.topLevel, code)
			}
			continue
		}
		if strings.HasPrefix(fn.Name, "fuzz_") {
			seeds := extractSeeds(fn)
			funcs = append(funcs, fuzzFunc{
				name:   fn.Name,
				fn:     fn,
				seeds:  seeds,
				params: fn.Params,
			})
		} else {
			helperFuncs = append(helperFuncs, g.genFuncDecl(fn))
		}
	}

	// Generate each fuzz target's body as an ordinary boxed function before the
	// imports are captured, so that a package a body is the only user of — a
	// `nab` reached from inside a fuzz target and nowhere else — is in the list
	// by the time the file that holds the bodies is written.
	for _, ff := range funcs {
		fuzzBodies = append(fuzzBodies, g.genFuzzBodyFunc(ff.fn))
	}

	// Ensure testing import is registered before capturing import names
	g.ensureImport("testing")

	// Generate helpers (main.go)
	var hb strings.Builder
	hb.WriteString("// Code generated by meow compiler. DO NOT EDIT.\n")
	hb.WriteString("package main\n\n")
	hb.WriteString("import meow \"github.com/135yshr/meow/runtime/meowrt\"\n")
	importNames := make([]string, 0, len(g.imports))
	for name := range g.imports {
		importNames = append(importNames, name)
	}
	sort.Strings(importNames)
	for _, name := range importNames {
		fmt.Fprintf(&hb, "import meow_%s \"%s\"\n", name, g.imports[name])
	}
	hb.WriteString("\n")
	for _, fn := range helperFuncs {
		hb.WriteString(fn)
		hb.WriteString("\n\n")
	}
	for _, body := range fuzzBodies {
		hb.WriteString(body)
		hb.WriteString("\n\n")
	}
	// suppress unused imports
	hb.WriteString("var _ = meow.NewNil\n")
	hb.WriteString("var _ = meow_testing.Judge\n")

	// Generate fuzz tests (main_test.go)
	//
	// Only `testing` and the runtime are imported here: the bodies live beside
	// the helpers in main.go, so whatever a program nabs is used there, and
	// importing it again in this file would be an import nothing uses.
	var fb strings.Builder
	fb.WriteString("// Code generated by meow compiler. DO NOT EDIT.\n")
	fb.WriteString("package main\n\n")
	fb.WriteString("import (\n")
	if len(funcs) > 0 {
		fb.WriteString("\t\"testing\"\n\n")
	}
	fb.WriteString("\tmeow \"github.com/135yshr/meow/runtime/meowrt\"\n")
	fb.WriteString(")\n\n")
	// suppress unused imports
	fb.WriteString("var _ = meow.NewNil\n\n")

	// Validate seed arity
	for _, ff := range funcs {
		// A fuzz target with no parameters has nothing to vary, and Go's
		// testing package answers one with a panic and a stack. Saying so here
		// is the difference between a message and a crash.
		if len(ff.params) == 0 {
			return "", "", nil, fmt.Errorf("Hiss! fuzz function %s takes no parameters, so there is nothing to fuzz, nya~", ff.name)
		}
		for i, seed := range ff.seeds {
			if len(seed) != len(ff.params) {
				return "", "", nil, fmt.Errorf("fuzz function %s: seed %d has %d values but function takes %d parameters", ff.name, i+1, len(seed), len(ff.params))
			}
		}
	}

	var names []string
	for _, ff := range funcs {
		goName := "Fuzz" + capitalizeFirst(strings.TrimPrefix(ff.name, "fuzz_"))
		names = append(names, goName)

		fmt.Fprintf(&fb, "func %s(f *testing.F) {\n", goName)

		// Add seeds
		for _, seed := range ff.seeds {
			seedArgs := make([]string, len(seed))
			for i, s := range seed {
				seedArgs[i] = g.fuzzSeedLiteral(s)
			}
			fmt.Fprintf(&fb, "\tf.Add(%s)\n", strings.Join(seedArgs, ", "))
		}

		// Generate Fuzz function
		fuzzParams := make([]string, len(ff.params))
		fuzzParamTypes := make([]string, len(ff.params))
		for i, p := range ff.params {
			typ := g.fuzzGoType(p)
			fuzzParams[i] = fmt.Sprintf("%s_raw %s", p.Name, typ)
			fuzzParamTypes[i] = typ
		}

		// The testing.T is not named t, so that a fuzz parameter called `t`
		// shadows nothing the generated failure report needs, and the name is
		// checked against this target's parameters, because they are converted
		// with := in the closure's own scope.
		tName := fuzzHandleName(ff.params)
		fmt.Fprintf(&fb, "\tf.Fuzz(func(%s *testing.T, %s) {\n", tName, strings.Join(fuzzParams, ", "))

		// Convert raw params to meow values
		argNames := make([]string, len(ff.params))
		for i, p := range ff.params {
			converter := g.fuzzConverter(fuzzParamTypes[i], p.Name+"_raw")
			fmt.Fprintf(&fb, "\t\t%s := %s\n", p.Name, converter)
			argNames[i] = p.Name
		}

		// Call the body and report a Furball it did not handle. A failure
		// reaching here is precisely what the fuzzer was run to find, so it
		// fails the case and names both the assertion and the input that
		// provoked it, rather than being unwound in silence.
		fmt.Fprintf(&fb, "\t\tif __f, __ok := meow.AsFurball(%s(%s)); __ok {\n", ff.name, strings.Join(argNames, ", "))
		fmt.Fprintf(&fb, "\t\t\t%s.Fatalf(%q, %s)\n", tName,
			fmt.Sprintf("Hiss! %s(%s) failed, nya~: %%s", ff.name, fuzzInputFormat(ff.params)),
			strings.Join(append(fuzzRawArgs(ff.params), "__f.Message"), ", "))
		fb.WriteString("\t\t}\n")

		fb.WriteString("\t})\n")
		fb.WriteString("}\n\n")
	}

	return hb.String(), fb.String(), names, nil
}

// genFuzzBodyFunc emits a fuzz target's body as an ordinary boxed Meow
// function: parameters as meow.Value, a meow.Value result.
//
// The body cannot be generated into the f.Fuzz closure, because genStmt ends
// every statement with `return __f` for a Furball, and that closure returns
// nothing — the compile error #143 is about. Giving the body a function of its
// own gives that return somewhere to go, and gives the closure a value to look
// at afterwards, which is how `meow test` already treats a test function's
// Furball.
//
// Seed calls are dropped: they are the corpus, handed to f.Add instead.
func (g *Generator) genFuzzBodyFunc(fn *ast.FuncStmt) string {
	body := make([]ast.Stmt, 0, len(fn.Body))
	for _, stmt := range fn.Body {
		if isSeedCall(stmt) {
			continue
		}
		body = append(body, stmt)
	}

	params := make([]string, len(fn.Params))
	names := make([]string, len(fn.Params))
	for i, p := range fn.Params {
		params[i] = p.Name + " meow.Value"
		names[i] = p.Name
	}
	defer g.enterBoxedScope(names...)()
	defer g.enterNestedScope()()

	var b strings.Builder
	fmt.Fprintf(&b, "func %s(%s) meow.Value {\n", fn.Name, strings.Join(params, ", "))
	b.WriteString(g.callerPrologue())
	b.WriteString(g.hoistNestedFuncs(body))
	for _, stmt := range body {
		b.WriteString("\t")
		b.WriteString(g.genStmt(stmt))
		b.WriteString("\n")
	}
	if !g.blockAlwaysReturns(body) {
		b.WriteString("\treturn meow.NewNil()\n")
	}
	b.WriteString("}")
	return b.String()
}

// fuzzInputFormat renders the parameter list of a failure report, as
// `a=%#v, b=%#v`. %#v so that the string the fuzzer found reads back as a Go
// literal, quoted and with its escapes visible.
// fuzzHandleName picks a name for the closure's *testing.T that none of this
// target's parameters can take. Each parameter arrives as <name>_raw and is
// converted to <name> with := in the closure's own scope, so a target written
// with a parameter called __t would redeclare the handle rather than shadow
// it, and the generated file would not compile.
func fuzzHandleName(params []ast.Param) string {
	taken := make(map[string]bool, len(params)*2)
	for _, p := range params {
		taken[p.Name] = true
		taken[p.Name+"_raw"] = true
	}
	name := "__t"
	for taken[name] {
		name += "_"
	}
	return name
}

func fuzzInputFormat(params []ast.Param) string {
	parts := make([]string, len(params))
	for i, p := range params {
		parts[i] = p.Name + "=%#v"
	}
	return strings.Join(parts, ", ")
}

// fuzzRawArgs names the raw Go values behind those parameters, which is what
// the report prints: the meow.Value boxes would only print their contents
// anyway, and these are what a reproducing corpus entry holds.
func fuzzRawArgs(params []ast.Param) []string {
	args := make([]string, len(params))
	for i, p := range params {
		args[i] = p.Name + "_raw"
	}
	return args
}

func extractSeeds(fn *ast.FuncStmt) [][]ast.Expr {
	var seeds [][]ast.Expr
	for _, stmt := range fn.Body {
		if es, ok := stmt.(*ast.ExprStmt); ok {
			if call, ok := es.Expr.(*ast.CallExpr); ok {
				if ident, ok := call.Fn.(*ast.Ident); ok && ident.Name == "seed" {
					seeds = append(seeds, call.Args)
				}
			}
		}
	}
	return seeds
}

func isSeedCall(stmt ast.Stmt) bool {
	es, ok := stmt.(*ast.ExprStmt)
	if !ok {
		return false
	}
	call, ok := es.Expr.(*ast.CallExpr)
	if !ok {
		return false
	}
	ident, ok := call.Fn.(*ast.Ident)
	return ok && ident.Name == "seed"
}

func (g *Generator) fuzzSeedLiteral(expr ast.Expr) string {
	switch e := expr.(type) {
	case *ast.IntLit:
		return fmt.Sprintf("int64(%d)", e.Value)
	case *ast.FloatLit:
		return fmt.Sprintf("float64(%g)", e.Value)
	case *ast.StringLit:
		return fmt.Sprintf("%q", e.Value)
	case *ast.BoolLit:
		return fmt.Sprintf("%t", e.Value)
	case *ast.UnaryExpr:
		if e.Op == token.MINUS {
			switch inner := e.Right.(type) {
			case *ast.IntLit:
				return fmt.Sprintf("int64(%d)", -inner.Value)
			case *ast.FloatLit:
				return fmt.Sprintf("float64(%g)", -inner.Value)
			}
		}
		return "int64(0)"
	default:
		return "int64(0)"
	}
}

// fuzzGoType returns the Go type string for a fuzz parameter based on its type annotation.
func (g *Generator) fuzzGoType(p ast.Param) string {
	if p.TypeAnn == nil {
		return "int64" // fallback
	}
	if bt, ok := p.TypeAnn.(*ast.BasicType); ok {
		switch bt.Name {
		case "int":
			return "int64"
		case "float":
			return "float64"
		case "string":
			return "string"
		case "bool":
			return "bool"
		}
	}
	return "int64"
}

func (g *Generator) fuzzConverter(typ, rawVar string) string {
	switch typ {
	case "int64":
		return fmt.Sprintf("meow.NewInt(%s)", rawVar)
	case "float64":
		return fmt.Sprintf("meow.NewFloat(%s)", rawVar)
	case "string":
		return fmt.Sprintf("meow.NewString(%s)", rawVar)
	case "bool":
		return fmt.Sprintf("meow.NewBool(%s)", rawVar)
	default:
		return fmt.Sprintf("meow.NewInt(%s)", rawVar)
	}
}
