// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ILLEGAL-0]
	_ = x[EOF-1]
	_ = x[COMMENT-2]
	_ = x[IDENT-3]
	_ = x[INT-4]
	_ = x[FLOAT-5]
	_ = x[STRING-6]
	_ = x[PLUS-7]
	_ = x[MINUS-8]
	_ = x[STAR-9]
	_ = x[SLASH-10]
	_ = x[PERCENT-11]
	_ = x[ASSIGN-12]
	_ = x[EQ-13]
	_ = x[NEQ-14]
	_ = x[LT-15]
	_ = x[GT-16]
	_ = x[LTE-17]
	_ = x[GTE-18]
	_ = x[AND-19]
	_ = x[OR-20]
	_ = x[NOT-21]
	_ = x[PIPE-22]
	_ = x[DOTDOT-23]
	_ = x[ARROW-24]
	_ = x[LPAREN-25]
	_ = x[RPAREN-26]
	_ = x[LBRACE-27]
	_ = x[RBRACE-28]
	_ = x[LBRACKET-29]
	_ = x[RBRACKET-30]
	_ = x[COMMA-31]
	_ = x[NEWLINE-32]
	_ = x[keywordsStart-33]
	_ = x[NYAN-34]
	_ = x[MEOW-35]
	_ = x[BRING-36]
	_ = x[SNIFF-37]
	_ = x[SCRATCH-38]
	_ = x[PURR-39]
	_ = x[PAW-40]
	_ = x[NYA-41]
	_ = x[LICK-42]
	_ = x[PICKY-43]
	_ = x[CURL-44]
	_ = x[PEEK-45]
	_ = x[HISS-46]
	_ = x[FETCH-47]
	_ = x[FLAUNT-48]
	_ = x[CATNAP-49]
	_ = x[YARN-50]
	_ = x[HAIRBALL-51]
	_ = x[keywordsEnd-52]
}

const _TokenType_name = "ILLEGALEOFCOMMENTIDENTINTFLOATSTRINGPLUSMINUSSTARSLASHPERCENTASSIGNEQNEQLTGTLTEGTEANDORNOTPIPEDOTDOTARROWLPARENRPARENLBRACERBRACELBRACKETRBRACKETCOMMANEWLINEkeywordsStartNYANMEOWBRINGSNIFFSCRATCHPURRPAWNYALICKPICKYCURLPEEKHISSFETCHFLAUNTCATNAPYARNHAIRBALLkeywordsEnd"

var _TokenType_index = [...]uint16{0, 7, 10, 17, 22, 25, 30, 36, 40, 45, 49, 54, 61, 67, 69, 72, 74, 76, 79, 82, 85, 87, 90, 94, 100, 105, 111, 117, 123, 129, 137, 145, 150, 157, 170, 174, 178, 183, 188, 195, 199, 202, 205, 209, 214, 218, 222, 226, 231, 237, 243, 247, 255, 266}

func (i TokenType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TokenType_index)-1 {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[idx]:_TokenType_index[idx+1]]
}
