// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ILLEGAL-0]
	_ = x[EOF-1]
	_ = x[COMMENT-2]
	_ = x[IDENT-3]
	_ = x[INT-4]
	_ = x[FLOAT-5]
	_ = x[STRING-6]
	_ = x[PLUS-7]
	_ = x[MINUS-8]
	_ = x[STAR-9]
	_ = x[SLASH-10]
	_ = x[PERCENT-11]
	_ = x[ASSIGN-12]
	_ = x[EQ-13]
	_ = x[NEQ-14]
	_ = x[LT-15]
	_ = x[GT-16]
	_ = x[LTE-17]
	_ = x[GTE-18]
	_ = x[AND-19]
	_ = x[OR-20]
	_ = x[NOT-21]
	_ = x[PIPE-22]
	_ = x[TILDEARROW-23]
	_ = x[DOT-24]
	_ = x[DOTDOT-25]
	_ = x[ARROW-26]
	_ = x[LPAREN-27]
	_ = x[RPAREN-28]
	_ = x[LBRACE-29]
	_ = x[RBRACE-30]
	_ = x[LBRACKET-31]
	_ = x[RBRACKET-32]
	_ = x[COMMA-33]
	_ = x[COLON-34]
	_ = x[NEWLINE-35]
	_ = x[keywordsStart-36]
	_ = x[NYAN-37]
	_ = x[MEOW-38]
	_ = x[BRING-39]
	_ = x[SNIFF-40]
	_ = x[SCRATCH-41]
	_ = x[PURR-42]
	_ = x[PAW-43]
	_ = x[NYA-44]
	_ = x[LICK-45]
	_ = x[PICKY-46]
	_ = x[CURL-47]
	_ = x[PEEK-48]
	_ = x[HISS-49]
	_ = x[FETCH-50]
	_ = x[FLAUNT-51]
	_ = x[CATNAP-52]
	_ = x[YARN-53]
	_ = x[HAIRBALL-54]
	_ = x[KITTY-55]
	_ = x[BREED-56]
	_ = x[COLLAR-57]
	_ = x[TYPE_INT-58]
	_ = x[TYPE_FLOAT-59]
	_ = x[TYPE_STRING-60]
	_ = x[TYPE_BOOL-61]
	_ = x[TYPE_FURBALL-62]
	_ = x[TYPE_LIST-63]
	_ = x[keywordsEnd-64]
}

const _TokenType_name = "ILLEGALEOFCOMMENTIDENTINTFLOATSTRINGPLUSMINUSSTARSLASHPERCENTASSIGNEQNEQLTGTLTEGTEANDORNOTPIPETILDEARROWDOTDOTDOTARROWLPARENRPARENLBRACERBRACELBRACKETRBRACKETCOMMACOLONNEWLINEkeywordsStartNYANMEOWBRINGSNIFFSCRATCHPURRPAWNYALICKPICKYCURLPEEKHISSFETCHFLAUNTCATNAPYARNHAIRBALLKITTYBREEDCOLLARTYPE_INTTYPE_FLOATTYPE_STRINGTYPE_BOOLTYPE_FURBALLTYPE_LISTkeywordsEnd"

var _TokenType_index = [...]uint16{0, 7, 10, 17, 22, 25, 30, 36, 40, 45, 49, 54, 61, 67, 69, 72, 74, 76, 79, 82, 85, 87, 90, 94, 104, 107, 113, 118, 124, 130, 136, 142, 150, 158, 163, 168, 175, 188, 192, 196, 201, 206, 213, 217, 220, 223, 227, 232, 236, 240, 244, 249, 255, 261, 265, 273, 278, 283, 289, 297, 307, 318, 327, 339, 348, 359}

func (i TokenType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TokenType_index)-1 {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[idx]:_TokenType_index[idx+1]]
}
