// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ILLEGAL-0]
	_ = x[EOF-1]
	_ = x[COMMENT-2]
	_ = x[IDENT-3]
	_ = x[INT-4]
	_ = x[FLOAT-5]
	_ = x[STRING-6]
	_ = x[PLUS-7]
	_ = x[MINUS-8]
	_ = x[STAR-9]
	_ = x[SLASH-10]
	_ = x[PERCENT-11]
	_ = x[ASSIGN-12]
	_ = x[EQ-13]
	_ = x[NEQ-14]
	_ = x[LT-15]
	_ = x[GT-16]
	_ = x[LTE-17]
	_ = x[GTE-18]
	_ = x[AND-19]
	_ = x[OR-20]
	_ = x[NOT-21]
	_ = x[PIPE-22]
	_ = x[TILDEARROW-23]
	_ = x[DOT-24]
	_ = x[DOTDOT-25]
	_ = x[ARROW-26]
	_ = x[LPAREN-27]
	_ = x[RPAREN-28]
	_ = x[LBRACE-29]
	_ = x[RBRACE-30]
	_ = x[LBRACKET-31]
	_ = x[RBRACKET-32]
	_ = x[COMMA-33]
	_ = x[NEWLINE-34]
	_ = x[keywordsStart-35]
	_ = x[NYAN-36]
	_ = x[MEOW-37]
	_ = x[BRING-38]
	_ = x[SNIFF-39]
	_ = x[SCRATCH-40]
	_ = x[PURR-41]
	_ = x[PAW-42]
	_ = x[NYA-43]
	_ = x[LICK-44]
	_ = x[PICKY-45]
	_ = x[CURL-46]
	_ = x[PEEK-47]
	_ = x[HISS-48]
	_ = x[FETCH-49]
	_ = x[FLAUNT-50]
	_ = x[CATNAP-51]
	_ = x[YARN-52]
	_ = x[HAIRBALL-53]
	_ = x[keywordsEnd-54]
}

const _TokenType_name = "ILLEGALEOFCOMMENTIDENTINTFLOATSTRINGPLUSMINUSSTARSLASHPERCENTASSIGNEQNEQLTGTLTEGTEANDORNOTPIPETILDEARROWDOTDOTDOTARROWLPARENRPARENLBRACERBRACELBRACKETRBRACKETCOMMANEWLINEkeywordsStartNYANMEOWBRINGSNIFFSCRATCHPURRPAWNYALICKPICKYCURLPEEKHISSFETCHFLAUNTCATNAPYARNHAIRBALLkeywordsEnd"

var _TokenType_index = [...]uint16{0, 7, 10, 17, 22, 25, 30, 36, 40, 45, 49, 54, 61, 67, 69, 72, 74, 76, 79, 82, 85, 87, 90, 94, 104, 107, 113, 118, 124, 130, 136, 142, 150, 158, 163, 170, 183, 187, 191, 196, 201, 208, 212, 215, 218, 222, 227, 231, 235, 239, 244, 250, 256, 260, 268, 279}

func (i TokenType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TokenType_index)-1 {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[idx]:_TokenType_index[idx+1]]
}
